import { PrismaClient } from '@prisma/client';
import { Difficulty, ExerciseType } from '../lib/types';
import { serializeJson } from '../lib/json-storage';

const prisma = new PrismaClient();

const topics = [
  ['sentence_structure','Sentence Structure','Building clear and grammatically complete sentences.','B1-C1'],
  ['verb_tenses','Verb Tenses','Using present, past, and future forms accurately.','B1-C1'],
  ['subject_verb_agreement','Subject-Verb Agreement','Matching verbs to subjects correctly.','B1-B2'],
  ['articles','Articles','Using a, an, and the in context.','B1-B2'],
  ['pronouns','Pronouns','Choosing correct subject, object, and possessive pronouns.','B1-B2'],
  ['prepositions','Prepositions','Using location/time and fixed prepositions correctly.','B1-C1'],
  ['countable_uncountable_nouns','Countable & Uncountable Nouns','Distinguishing noun countability and quantifiers.','B1-B2'],
  ['gerunds_infinitives','Gerunds & Infinitives','Selecting gerund/infinitive verb patterns.','B1-C1'],
  ['modals','Modals','Using can, should, must, and related modal verbs.','B1-C1'],
  ['conjunctions_linking_words','Conjunctions & Linking Words','Connecting ideas with logical linkers.','B1-C1'],
  ['conditionals','Conditionals','Using zero, first, second, and third conditionals.','B2-C1'],
  ['comparatives_superlatives','Comparatives & Superlatives','Comparing people, places, and ideas.','B1-B2'],
  ['relative_clauses','Relative Clauses','Adding detail with who/which/that/whose clauses.','B2-C1'],
  ['passive_voice','Passive Voice','Forming passive structures across tenses.','B2-C1'],
  ['perfect_tenses','Perfect Tenses','Using present/past perfect and perfect continuous forms.','B2-C1'],
  ['question_forms','Question Forms','Building direct and indirect questions correctly.','B1-B2'],
  ['noun_clauses','Noun Clauses','Using clauses as subjects/objects/complements.','B2-C1'],
  ['verb_patterns','Verb Patterns','Collocations and grammar patterns after verbs.','B2-C1'],
  ['reported_speech','Reported Speech','Converting direct to reported statements/questions.','B2-C1'],
  ['irregular_verbs_past_simple','Irregular Verbs — Past Simple','Common irregular verb forms in past simple in practical Canadian contexts.','B1-B2'],
  ['irregular_verbs_present_perfect','Irregular Verbs — Present Perfect','Present perfect with irregular past participles (have/has + V3) in realistic contexts.','B1-C1'],
  ['adjectives_adverbs_manner','Adjectives & Adverbs — Manner and Placement','Choosing adjective vs adverb, common -ly forms, irregular adverbs, and placement.','B1-C1'],
  ['relative_words_choice','Relative Words — who, which, that, whose, where, what, whom','Choosing the most appropriate relative or question word depending on meaning and grammar function.','B1-C1'],
  ['enough_usage','Enough — form and placement','Practice with enough after adjectives/adverbs and before nouns, including meaning and sentence structure.','B1-B2'],
  ['obligation_modals','Obligation — must, have to, should, need to, be supposed to','Expressing obligation, necessity, strong advice, rules, and expectations in practical contexts.','B1-C1'],
  ['going_to_vs_will','Future Forms — going to vs will','Choosing between going to and will for plans, intentions, predictions, decisions, and spontaneous reactions.','B1-B2']
] as const;

type SeedExercise = {
  topicSlug: string;
  difficulty: Difficulty;
  type: ExerciseType;
  prompt: string;
  instructions: string;
  questionData: object;
  correctAnswer: object;
  explanationCorrect: string;
  explanationWrong: string;
  ruleSummary: string;
  extraExample: string;
};


const VALID_DIFFICULTIES: Difficulty[] = ['intermediate', 'advanced'];
const VALID_TYPES: ExerciseType[] = ['multiple_choice', 'fill_blank', 'error_correction', 'mini_production'];
const REQUIRED_FIELDS = [
  'topicSlug',
  'difficulty',
  'type',
  'prompt',
  'instructions',
  'questionData',
  'correctAnswer',
  'explanationCorrect',
  'explanationWrong',
  'ruleSummary',
  'extraExample',
] as const;

function validateSeedData() {
  const topicSlugs = new Set(topics.map(([slug]) => slug));

  for (const [index, ex] of exercises.entries()) {
    for (const key of REQUIRED_FIELDS) {
      const value = (ex as Record<string, unknown>)[key];
      if (value === undefined || value === null || value === '') {
        throw new Error(`Exercise #${index + 1} is missing required field: ${key}`);
      }
    }

    if (!topicSlugs.has(ex.topicSlug)) {
      throw new Error(`Exercise #${index + 1} references unknown topic slug: ${ex.topicSlug}`);
    }

    if (!VALID_DIFFICULTIES.includes(ex.difficulty)) {
      throw new Error(`Exercise #${index + 1} has invalid difficulty: ${ex.difficulty}`);
    }

    if (!VALID_TYPES.includes(ex.type)) {
      throw new Error(`Exercise #${index + 1} has invalid type: ${ex.type}`);
    }
  }

  const perTopicCount = new Map<string, number>();
  for (const ex of exercises) {
    perTopicCount.set(ex.topicSlug, (perTopicCount.get(ex.topicSlug) ?? 0) + 1);
  }

  for (const [slug] of topics) {
    if (!perTopicCount.has(slug)) {
      // topic can still be valid with zero exercises, but report clearly in seed logs
      console.warn(`Warning: topic "${slug}" has 0 seeded exercises.`);
    }
  }
}


const exercises: SeedExercise[] = [
  { topicSlug:'conditionals', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'If I were you, I ___ talk to the manager before making a complaint online.', options:['A. will','B. would','C. had','D. have'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'In the second conditional, use "would" in the result clause: If I were you, I would...', explanationWrong:'Other options break second conditional form.', ruleSummary:'Second conditional = If + past simple, would + base verb.', extraExample:'If I had more time, I would take an evening class.' },
  { topicSlug:'articles', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'She bought ___ umbrella because it was raining.', options:['A. a','B. an','C. the','D. no article'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'"Umbrella" starts with a vowel sound, so we use "an".', explanationWrong:'"a" cannot be used before a vowel sound.', ruleSummary:'Use "an" before vowel sounds.', extraExample:'He saw an accident on the way to work.' },
  { topicSlug:'subject_verb_agreement', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'One of my classmates ___ studying for the CELPIP exam this month.', options:['A. are','B. were','C. is','D. be'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'The subject is "one", which is singular, so the verb must be singular: "is".', explanationWrong:'Plural verbs do not agree with singular "one".', ruleSummary:'The verb agrees with the true subject, not the noun after "of".', extraExample:'One of my friends is moving to Calgary.' },
  { topicSlug:'prepositions', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I am interested ___ taking a short course in business writing.', options:['A. on','B. at','C. in','D. for'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'The correct collocation is "interested in".', explanationWrong:'Other prepositions are not used with "interested" in this meaning.', ruleSummary:'Many adjectives require fixed prepositions.', extraExample:'She is good at solving practical problems.' },
  { topicSlug:'gerunds_infinitives', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I enjoy ___ with people from different backgrounds.', options:['A. talk','B. to talk','C. talking','D. talked'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'"Enjoy" is followed by a gerund (-ing form).', explanationWrong:'Infinitive/base forms are incorrect after "enjoy".', ruleSummary:'Some verbs are followed by gerunds, not infinitives.', extraExample:'He avoids driving during rush hour.' },
  { topicSlug:'perfect_tenses', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'By the time I arrived, the workshop ___ already ___.', options:['A. has / started','B. had / started','C. was / starting','D. did / start'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Use the past perfect for an action completed before another action in the past.', explanationWrong:'Other options do not express earlier completed action properly.', ruleSummary:'Past perfect = had + past participle.', extraExample:'By the time we got there, the movie had already ended.' },
  { topicSlug:'passive_voice', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The final decision ___ by the hiring committee next week.', options:['A. makes','B. made','C. will be made','D. is making'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'This is a future passive structure: will be made.', explanationWrong:'Active forms do not fit this passive sentence.', ruleSummary:'Passive voice = be + past participle.', extraExample:'The results will be announced on Friday.' },
  { topicSlug:'noun_clauses', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'What I find most frustrating ___ the lack of clear communication.', options:['A. are','B. were','C. is','D. have been'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'The clause "What I find most frustrating" is treated as singular here.', explanationWrong:'Plural verbs are not suitable with this clause subject.', ruleSummary:'Noun clauses often function as singular subjects.', extraExample:'What matters most is consistency.' },
  { topicSlug:'relative_clauses', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The professor ___ taught that grammar workshop is retiring this year.', options:['A. which','B. whose','C. whom','D. who'], answerKey:'D' }, correctAnswer:{ answer:'D' }, explanationCorrect:'Use "who" for people as the subject of a relative clause.', explanationWrong:'"which" is for things, and "whom" is object form.', ruleSummary:'Use who for people, which for things, whose for possession.', extraExample:'The colleague who helped me was very patient.' },
  { topicSlug:'reported_speech', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'She said that she ___ the assignment the night before.', options:['A. finishes','B. had finished','C. has finished','D. finish'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'In reported speech, backshift is often needed when the reporting verb is in the past.', explanationWrong:'Other forms do not match typical backshift here.', ruleSummary:'Direct past can shift to past perfect in reported speech.', extraExample:'He told me that he had already sent the email.' },
  { topicSlug:'modals', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'You ___ speak to your instructor as soon as possible if you need an extension.', expectedAnswer:'should', acceptedAnswers:['should'] }, correctAnswer:{ answer:'should' }, explanationCorrect:'"Should" is used to give advice.', explanationWrong:'Other modal forms change the intended meaning.', ruleSummary:'Use "should" for advice.', extraExample:'You should check the schedule before leaving home.' },
  { topicSlug:'pronouns', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'Maria said that the blue backpack was ___, not mine.', expectedAnswer:'hers', acceptedAnswers:['hers'] }, correctAnswer:{ answer:'hers' }, explanationCorrect:'A possessive pronoun replaces a possessive noun phrase.', explanationWrong:'Object/subject pronouns are incorrect in this slot.', ruleSummary:'Use a possessive pronoun when the noun is omitted.', extraExample:'This jacket is his, but that one is hers.' },
  { topicSlug:'countable_uncountable_nouns', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'We do not have much ___ about the new immigration policy yet.', expectedAnswer:'information', acceptedAnswers:['information'] }, correctAnswer:{ answer:'information' }, explanationCorrect:'"Information" is an uncountable noun.', explanationWrong:'Pluralized countable forms are not correct here.', ruleSummary:'"Information" is uncountable.', extraExample:'They gave us useful information about the process.' },
  { topicSlug:'conjunctions_linking_words', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'I wanted to go to class; ___, I stayed home because my daughter was sick.', expectedAnswer:'however', acceptedAnswers:['however'] }, correctAnswer:{ answer:'however' }, explanationCorrect:'"However" introduces contrast between two ideas.', explanationWrong:'Other connectors may not show contrast.', ruleSummary:'Use "however" to express contrast.', extraExample:'The training was long; however, it was worth it.' },
  { topicSlug:'question_forms', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'Where ___ you work before you moved to Canada?', expectedAnswer:'did', acceptedAnswers:['did'] }, correctAnswer:{ answer:'did' }, explanationCorrect:'Simple past questions use auxiliary "did".', explanationWrong:'Using present auxiliaries creates tense mismatch.', ruleSummary:'Use "did" for simple past questions.', extraExample:'What did you study in college?' },
  { topicSlug:'conditionals', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'If they had prepared better, they ___ not have missed the deadline.', expectedAnswer:'would', acceptedAnswers:['would'] }, correctAnswer:{ answer:'would' }, explanationCorrect:'Third conditional result clause uses would have + participle.', explanationWrong:'Other modals do not match standard third conditional form.', ruleSummary:'Third conditional = If + had + participle, would have + participle.', extraExample:'If I had known, I would have called earlier.' },
  { topicSlug:'verb_patterns', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'I recommend ___ a short break before continuing your revision.', expectedAnswer:'taking', acceptedAnswers:['taking'] }, correctAnswer:{ answer:'taking' }, explanationCorrect:'"Recommend" commonly takes a gerund.', explanationWrong:'Infinitive form is less standard in this structure.', ruleSummary:'"Recommend" is commonly followed by a gerund.', extraExample:'I recommend using a planner for your weekly study goals.' },
  { topicSlug:'relative_clauses', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'The neighborhood in ___ we used to live has changed a lot.', expectedAnswer:'which', acceptedAnswers:['which'] }, correctAnswer:{ answer:'which' }, explanationCorrect:'After a preposition, "which" is preferred for things/places.', explanationWrong:'"That" generally does not follow a preposition directly here.', ruleSummary:'After a preposition, "which" is preferred for things/places.', extraExample:'The company for which she works is expanding.' },
  { topicSlug:'perfect_tenses', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'I ___ been trying to improve my speaking fluency for several months.', expectedAnswer:'have', acceptedAnswers:['have'] }, correctAnswer:{ answer:'have' }, explanationCorrect:'Present perfect continuous requires have/has + been + verb-ing.', explanationWrong:'Missing auxiliary makes the tense incorrect.', ruleSummary:'Present perfect continuous = have/has been + verb-ing.', extraExample:'She has been working on her portfolio since January.' },
  { topicSlug:'reported_speech', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct grammar form.', instructions:'Type your answer.', questionData:{ sentenceWithBlank:'He told me that he ___ unable to attend the meeting the following day.', expectedAnswer:'was', acceptedAnswers:['was'] }, correctAnswer:{ answer:'was' }, explanationCorrect:'Backshift in reported speech often changes is/am to was.', explanationWrong:'Present form does not align with past reporting.', ruleSummary:'In reported speech, "am/is" often shifts to "was" when reported in the past.', extraExample:'She said that she was feeling much better.' },
  { topicSlug:'verb_tenses', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'Yesterday I go to the bank after class.', expectedCorrection:'Yesterday I went to the bank after class.', acceptedCorrections:['Yesterday I went to the bank after class.'], errorFocus:'simple past' }, correctAnswer:{ answer:'Yesterday I went to the bank after class.' }, explanationCorrect:'The verb should be in simple past: went.', explanationWrong:'Base form "go" is wrong with "Yesterday".', ruleSummary:'Use the past form for finished actions in the past.', extraExample:'Last week we visited some friends in Burnaby.' },
  { topicSlug:'articles', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'He is looking for an new apartment near the station.', expectedCorrection:'He is looking for a new apartment near the station.', acceptedCorrections:['He is looking for a new apartment near the station.'], errorFocus:'article usage' }, correctAnswer:{ answer:'He is looking for a new apartment near the station.' }, explanationCorrect:'"New" starts with consonant sound, so use "a".', explanationWrong:'"an" before consonant sound is incorrect.', ruleSummary:'Use "a" before consonant sounds, "an" before vowel sounds.', extraExample:'She adopted a cat last summer.' },
  { topicSlug:'subject_verb_agreement', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'My sister work in a dental clinic downtown.', expectedCorrection:'My sister works in a dental clinic downtown.', acceptedCorrections:['My sister works in a dental clinic downtown.'], errorFocus:'subject-verb agreement' }, correctAnswer:{ answer:'My sister works in a dental clinic downtown.' }, explanationCorrect:'Third-person singular takes verb + s in present simple.', explanationWrong:'"work" without -s is incorrect for "my sister".', ruleSummary:'Third person singular in the simple present usually takes -s.', extraExample:'He drives to work every morning.' },
  { topicSlug:'prepositions', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'We arrived to the airport very early.', expectedCorrection:'We arrived at the airport very early.', acceptedCorrections:['We arrived at the airport very early.'], errorFocus:'fixed preposition' }, correctAnswer:{ answer:'We arrived at the airport very early.' }, explanationCorrect:'Use "arrive at" for specific places.', explanationWrong:'"arrive to" is not standard.', ruleSummary:'Use "arrive at" for specific places/buildings and "arrive in" for cities/countries.', extraExample:'They arrived in Toronto late at night.' },
  { topicSlug:'gerunds_infinitives', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'She decided taking the bus instead of driving.', expectedCorrection:'She decided to take the bus instead of driving.', acceptedCorrections:['She decided to take the bus instead of driving.'], errorFocus:'infinitive pattern' }, correctAnswer:{ answer:'She decided to take the bus instead of driving.' }, explanationCorrect:'"Decide" is followed by infinitive.', explanationWrong:'Gerund after "decided" is incorrect here.', ruleSummary:'"Decide" is followed by an infinitive.', extraExample:'I decided to apply for the weekend course.' },
  { topicSlug:'passive_voice', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'The documents will submitted tomorrow morning.', expectedCorrection:'The documents will be submitted tomorrow morning.', acceptedCorrections:['The documents will be submitted tomorrow morning.'], errorFocus:'passive structure' }, correctAnswer:{ answer:'The documents will be submitted tomorrow morning.' }, explanationCorrect:'Future passive needs "will be" + participle.', explanationWrong:'Missing "be" breaks passive construction.', ruleSummary:'Future passive = will be + past participle.', extraExample:'The final version will be reviewed by the supervisor.' },
  { topicSlug:'noun_clauses', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'What she needs are more time to practice.', expectedCorrection:'What she needs is more time to practice.', acceptedCorrections:['What she needs is more time to practice.'], errorFocus:'noun clause agreement' }, correctAnswer:{ answer:'What she needs is more time to practice.' }, explanationCorrect:'The noun clause subject is singular; use "is".', explanationWrong:'"are" does not agree with clause subject.', ruleSummary:'A noun clause subject is often singular.', extraExample:'What I want is a clear plan.' },
  { topicSlug:'relative_clauses', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'The man which interviewed me was very respectful.', expectedCorrection:'The man who interviewed me was very respectful.', acceptedCorrections:['The man who interviewed me was very respectful.'], errorFocus:'relative pronouns' }, correctAnswer:{ answer:'The man who interviewed me was very respectful.' }, explanationCorrect:'Use "who" for people.', explanationWrong:'"which" is used for things.', ruleSummary:'Use "who" for people.', extraExample:'The teacher who explained it was very clear.' },
  { topicSlug:'conditionals', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'If I would have known about the change, I would come earlier.', expectedCorrection:'If I had known about the change, I would have come earlier.', acceptedCorrections:['If I had known about the change, I would have come earlier.'], errorFocus:'third conditional' }, correctAnswer:{ answer:'If I had known about the change, I would have come earlier.' }, explanationCorrect:'Third conditional: If + had + participle, would have + participle.', explanationWrong:'Do not use "would" in the if-clause.', ruleSummary:'Do not use "would" in the if-clause of standard conditionals.', extraExample:'If we had left earlier, we would have caught the train.' },
  { topicSlug:'reported_speech', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'She said me that she was tired.', expectedCorrection:'She told me that she was tired.', acceptedCorrections:['She told me that she was tired.'], errorFocus:'reporting verbs' }, correctAnswer:{ answer:'She told me that she was tired.' }, explanationCorrect:'Use "told" when including a person object.', explanationWrong:'"said me" is ungrammatical.', ruleSummary:'Say + something; tell + someone + something.', extraExample:'He told me that the office was closed.' },
  { topicSlug:'modals', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'Your classmate is feeling overwhelmed before an English test.', task:'Give two pieces of advice using "should".', targetGrammar:'modals for advice', modelAnswer:'You should make a short study plan for tonight. You should also go to bed early so you can focus tomorrow.', keyPointsChecklist:['includes "should" at least twice','gives practical advice','uses clear sentence structure'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Compare your answer with the model and checklist.', explanationWrong:'If key checklist items are missing, revise your response.', ruleSummary:'Use modals to offer clear, practical advice.', extraExample:'You should review key vocabulary before class.' },
  { topicSlug:'conditionals', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'A friend wants to quit a part-time job without notice because he is frustrated.', task:'Give advice using "If I were you, I would..."', targetGrammar:'second conditional for advice', modelAnswer:'If I were you, I would speak to the manager first. I would also give proper notice instead of leaving suddenly.', keyPointsChecklist:['uses "If I were you"','uses "would"','gives 1 or 2 realistic suggestions'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Use second conditional to make polite advice.', explanationWrong:'Missing the target structure reduces grammar focus.', ruleSummary:'Second conditional can soften advice.', extraExample:'If I were you, I would ask for feedback first.' },
  { topicSlug:'conjunctions_linking_words', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'Your teacher asks whether online learning is effective.', task:'Write 3 to 4 sentences using at least one contrast linker.', targetGrammar:'contrast linker', modelAnswer:'Online learning is convenient because people can study from home. However, it can be difficult to stay focused for long periods. In my opinion, it works best when students follow a routine.', keyPointsChecklist:['includes a contrast linker','expresses an opinion','has at least 3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Contrast linkers improve coherence and argument balance.', explanationWrong:'Without contrast, response may be one-sided.', ruleSummary:'Use conjunctions/linkers to connect and contrast ideas.', extraExample:'The class is demanding; however, it is very useful.' },
  { topicSlug:'question_forms', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'You need information about a weekend workshop.', task:'Write 3 polite questions.', targetGrammar:'question formation', modelAnswer:'What time does the workshop start? How much does it cost? Do I need to register in advance?', keyPointsChecklist:['includes 3 questions','uses correct word order','punctuation is correct'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Check auxiliary placement and punctuation in each question.', explanationWrong:'Word-order mistakes reduce clarity and correctness.', ruleSummary:'Question forms require auxiliary + subject in most direct questions.', extraExample:'Can you tell me when the class begins?' },
  { topicSlug:'articles', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'Describe an item you recently bought for your studies.', task:'Write 3 to 4 sentences using a/an/the correctly.', targetGrammar:'articles', modelAnswer:'I recently bought a notebook and a set of pens. The notebook is small, but it is very useful. I keep it in my backpack every day.', keyPointsChecklist:['uses a/an/the correctly','includes 3 sentences minimum','context is clear'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Article control helps precision and naturalness.', explanationWrong:'Missing or wrong articles can make sentences awkward.', ruleSummary:'Choose a/an for new singular count nouns and the for specific reference.', extraExample:'I bought a dictionary. The dictionary is very helpful.' },
  { topicSlug:'passive_voice', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'Your workplace is introducing a new policy.', task:'Write 3 to 4 sentences explaining the change using at least one passive sentence.', targetGrammar:'passive voice', modelAnswer:'A new attendance policy will be introduced next month. Employees will be informed by email. The final version will be shared after the managers review it.', keyPointsChecklist:['includes at least one passive sentence','uses formal tone','has 3 sentences minimum'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Passive voice is useful for formal announcements.', explanationWrong:'If no passive form appears, target grammar is missing.', ruleSummary:'Passive = be + past participle; focus on action/result.', extraExample:'The guidelines were updated last week.' },
  { topicSlug:'relative_clauses', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'Describe a teacher, coworker, or mentor who helped you improve.', task:'Write 3 to 4 sentences using at least one relative clause.', targetGrammar:'relative clauses', modelAnswer:'I had a teacher who always gave detailed feedback. She created exercises that matched my level. She was one of the people who helped me become more confident in English.', keyPointsChecklist:['includes who/that/which/whose correctly','at least 3 sentences','meaning is clear'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Relative clauses combine ideas with precision.', explanationWrong:'Without a relative clause, target objective is unmet.', ruleSummary:'Use who/which/that/whose to add defining details.', extraExample:'I met a mentor who encouraged me to keep practicing.' },
  { topicSlug:'perfect_tenses', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'Explain how your English has changed since you moved to Canada.', task:'Write 3 to 5 sentences using at least one present perfect sentence.', targetGrammar:'present perfect', modelAnswer:'I have improved my listening a lot since I moved to Canada. I have also become more confident in everyday conversations. However, I still need to work on my speaking under pressure.', keyPointsChecklist:['includes present perfect correctly','links past to present','minimum 3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Present perfect links life experience to now.', explanationWrong:'Only simple past may miss ongoing relevance.', ruleSummary:'Present perfect often combines with since/for to connect past and present.', extraExample:'I have studied English for three years.' },
  { topicSlug:'noun_clauses', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'Give your opinion about what makes a good language-learning routine.', task:'Write 3 to 4 sentences using at least one noun clause.', targetGrammar:'noun clauses', modelAnswer:'What matters most is consistency. What many learners forget is that small daily practice can be very powerful. I think a good routine should be realistic and sustainable.', keyPointsChecklist:['includes one noun clause','idea is coherent','minimum 3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Noun clauses support complex, academic-style expression.', explanationWrong:'If no noun clause is present, grammar target is not met.', ruleSummary:'Noun clauses can function as subject/object/complement.', extraExample:'What I need is a realistic weekly plan.' },
  { topicSlug:'reported_speech', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar in 3-4 sentences.', questionData:{ scenario:'You are telling a friend what your instructor said about improving writing.', task:'Write 3 to 4 sentences using reported speech.', targetGrammar:'reported speech', modelAnswer:'My instructor said that I needed to organize my ideas more clearly. She told me that strong topic sentences make a big difference. She also said that I should review my grammar before submitting my work.', keyPointsChecklist:['includes reported speech','uses said/told correctly','meaning remains clear'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Reported speech helps summarize advice and feedback accurately.', explanationWrong:'Incorrect reporting verbs reduce correctness.', ruleSummary:'Use said/told structures carefully and apply backshift when needed.', extraExample:'He said that he would revise his essay.' },

  { topicSlug:'irregular_verbs_past_simple', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'Yesterday, I ___ the SkyTrain to downtown Vancouver.', options:['A. take','B. took','C. taken','D. taking'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Past simple of “take” is “took”.', explanationWrong:'“Taken” is a past participle, not past simple.', ruleSummary:'Use past simple for finished actions in the past.', extraExample:'I took my daughter to the park last weekend.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I have ___ this email twice, but I still think it sounds too direct.', options:['A. wrote','B. written','C. write','D. writing'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Present perfect = have/has + past participle (“written”).', explanationWrong:'“Wrote” is past simple, not V3.', ruleSummary:'Present perfect uses V3 (past participle).', extraExample:'She has written three job applications this week.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'By the time the meeting started, our manager had already ___ the key points.', options:['A. said','B. say','C. saying','D. says'], answerKey:'A' }, correctAnswer:{ answer:'A' }, explanationCorrect:'Past perfect uses had + V3; “said” is V3.', explanationWrong:'Other options are not correct past participle forms in this structure.', ruleSummary:'Past perfect = had + past participle.', extraExample:'He had told us about the change earlier.' },
  { topicSlug:'irregular_verbs_past_simple', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The contractor ___ the window yesterday, so we had to call the building manager.', options:['A. broke','B. broken','C. break','D. breaking'], answerKey:'A' }, correctAnswer:{ answer:'A' }, explanationCorrect:'Past simple of “break” is “broke”.', explanationWrong:'“Broken” is V3 and needs have/has/had.', ruleSummary:'Past simple uses V2 for irregular verbs.', extraExample:'Someone broke my phone screen last month.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'We have not ___ a decision yet because we need more information.', options:['A. made','B. make','C. making','D. makes'], answerKey:'A' }, correctAnswer:{ answer:'A' }, explanationCorrect:'Present perfect negative: have not + V3 (“made”).', explanationWrong:'Base form does not follow “have” in present perfect.', ruleSummary:'have/has + past participle (V3).', extraExample:'They have not chosen a date yet.' },

  { topicSlug:'irregular_verbs_past_simple', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'Last night, I ___ (go) to bed early because I was exhausted.', expectedAnswer:'went', acceptedAnswers:['went'] }, correctAnswer:{ answer:'went' }, explanationCorrect:'Past simple of “go” is “went”.', explanationWrong:'Regular -ed form is incorrect for this irregular verb.', ruleSummary:'Past simple of “go” is “went”.', extraExample:'We went to Whistler in January.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'I have ___ (see) that movie, but I do not remember the ending.', expectedAnswer:'seen', acceptedAnswers:['seen'] }, correctAnswer:{ answer:'seen' }, explanationCorrect:'Present perfect needs V3: see → seen.', explanationWrong:'“Saw” is past simple, not V3.', ruleSummary:'Present perfect uses V3: see → seen.', extraExample:'Have you seen the new schedule?' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'She has ___ (begin) studying earlier, so she feels calmer now.', expectedAnswer:'begun', acceptedAnswers:['begun'] }, correctAnswer:{ answer:'begun' }, explanationCorrect:'Begin → began (past) → begun (V3).', explanationWrong:'“Began” cannot be used after has in present perfect.', ruleSummary:'begin → began (past) → begun (V3).', extraExample:'They have begun a new training program.' },
  { topicSlug:'irregular_verbs_past_simple', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'He ___ (drive) to Surrey yesterday for an appointment.', expectedAnswer:'drove', acceptedAnswers:['drove'] }, correctAnswer:{ answer:'drove' }, explanationCorrect:'Drive → drove in past simple.', explanationWrong:'Driven is V3, not V2.', ruleSummary:'drive → drove (past) → driven (V3).', extraExample:'I drove to work because it was raining.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'We have ___ (eat) at that restaurant before; the service was excellent.', expectedAnswer:'eaten', acceptedAnswers:['eaten'] }, correctAnswer:{ answer:'eaten' }, explanationCorrect:'Present perfect needs V3: eaten.', explanationWrong:'Ate is past simple, not V3.', ruleSummary:'eat → ate (past) → eaten (V3).', extraExample:'She has eaten lunch already.' },

  { topicSlug:'irregular_verbs_past_simple', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'Yesterday I goed to the library after class.', expectedCorrection:'Yesterday I went to the library after class.', acceptedCorrections:['Yesterday I went to the library after class.'], errorFocus:'irregular past (go → went)' }, correctAnswer:{ answer:'Yesterday I went to the library after class.' }, explanationCorrect:'Irregular past of go is went.', explanationWrong:'“Goed” is not a valid English form.', ruleSummary:'Some verbs do not take -ed in the past.', extraExample:'I went to a workshop last week.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'I have saw that email already.', expectedCorrection:'I have seen that email already.', acceptedCorrections:['I have seen that email already.'], errorFocus:'V3 after have/has' }, correctAnswer:{ answer:'I have seen that email already.' }, explanationCorrect:'After have/has, use past participle.', explanationWrong:'“Saw” is V2, not V3.', ruleSummary:'Present perfect requires past participle (V3).', extraExample:'I have seen the updated policy.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'She has went to the doctor twice this month.', expectedCorrection:'She has gone to the doctor twice this month.', acceptedCorrections:['She has gone to the doctor twice this month.'], errorFocus:'go → gone (V3)' }, correctAnswer:{ answer:'She has gone to the doctor twice this month.' }, explanationCorrect:'Present perfect requires gone (V3).', explanationWrong:'Went is V2 and cannot follow has here.', ruleSummary:'go → went (past) → gone (V3).', extraExample:'He has gone home already.' },
  { topicSlug:'irregular_verbs_past_simple', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'He has wrote the report yesterday.', expectedCorrection:'He wrote the report yesterday.', acceptedCorrections:['He wrote the report yesterday.'], errorFocus:'tense mismatch with yesterday' }, correctAnswer:{ answer:'He wrote the report yesterday.' }, explanationCorrect:'“Yesterday” needs past simple, not present perfect.', explanationWrong:'Has wrote is grammatically incorrect and mismatched tense.', ruleSummary:'Use past simple with finished past time markers.', extraExample:'I finished the form yesterday.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'We have choose a new laptop for the office.', expectedCorrection:'We have chosen a new laptop for the office.', acceptedCorrections:['We have chosen a new laptop for the office.'], errorFocus:'choose → chosen (V3)' }, correctAnswer:{ answer:'We have chosen a new laptop for the office.' }, explanationCorrect:'Present perfect uses chosen (V3).', explanationWrong:'Choose is base form and cannot follow have directly here.', ruleSummary:'Present perfect requires V3.', extraExample:'They have chosen a better option.' },

  { topicSlug:'irregular_verbs_past_simple', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You are telling a friend about a busy day yesterday.', task:'Write 3 sentences using at least two irregular verbs in past simple (went, took, met, bought, etc.).', targetGrammar:'Past simple irregular verbs', modelAnswer:'Yesterday, I went to a medical appointment. I took the bus because it was raining. After that, I met a friend for coffee.', keyPointsChecklist:['use 2+ irregular past forms','clear time marker','3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Good job if you used irregular past forms correctly with clear past context.', explanationWrong:'Revise your response if it lacks irregular past forms or clear past-time reference.', ruleSummary:'Use irregular V2 forms for completed past actions.', extraExample:'I bought groceries and then met my classmate.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You are updating your instructor on your progress this week.', task:'Write 3 sentences using present perfect with irregular verbs (have/has + V3).', targetGrammar:'Present perfect irregular verbs', modelAnswer:'I have written two practice emails this week. I have begun reviewing my weak grammar topics. I have seen improvement in my confidence.', keyPointsChecklist:['use have/has + V3','include “this week”','3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Strong if each sentence uses have/has + irregular V3 clearly.', explanationWrong:'Revise if you used past simple instead of present perfect.', ruleSummary:'Present perfect = have/has + V3, often for recent progress.', extraExample:'I have made fewer mistakes this week.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You are explaining recent changes since moving to Canada.', task:'Write 4 sentences using present perfect with since/for and at least two irregular V3 forms.', targetGrammar:'Present perfect + since/for', modelAnswer:'I have lived in Metro Vancouver for almost two years. I have made new friends since I started college. I have learned to manage my time better. I have taken more speaking practice seriously.', keyPointsChecklist:['include since/for','2+ irregular V3','4 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Great if you linked past-to-present using since/for and irregular V3 forms.', explanationWrong:'Revise if since/for or irregular V3 usage is missing.', ruleSummary:'Use present perfect for ongoing life changes up to now.', extraExample:'I have become more confident since joining this program.' },
  { topicSlug:'irregular_verbs_past_simple', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Tell a short story about a mistake you made last month.', task:'Write 4 sentences using past simple with at least two irregular verbs.', targetGrammar:'Past simple irregular verbs', modelAnswer:'Last month, I forgot an important deadline. I wrote the wrong date in my calendar. I felt stressed, but I fixed it quickly. In the end, I learned a lesson.', keyPointsChecklist:['include “last month”','2+ irregular past','4 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Good response if it stays in past simple with correct irregular forms.', explanationWrong:'Revise if verb forms mix tenses inappropriately.', ruleSummary:'Past simple narrates completed past events.', extraExample:'Last month, I took the wrong bus and missed class.' },
  { topicSlug:'irregular_verbs_present_perfect', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You are describing what has happened so far today.', task:'Write 3–4 sentences using present perfect with just/already/yet.', targetGrammar:'Present perfect markers', modelAnswer:'I have already checked my emails. I have just finished a short grammar exercise. I have not started my writing task yet, but I will soon.', keyPointsChecklist:['use already/just/yet correctly','have/has + V3'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Strong if you used present perfect markers naturally.', explanationWrong:'Revise if marker placement or tense is incorrect.', ruleSummary:'Use just/already/yet with present perfect for recent status.', extraExample:'I have already done my vocabulary review today.' },

  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'She speaks English very ___ when she is calm.', options:['A. fluent','B. fluently','C. fluency','D. more fluent'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'“Speaks” is a verb, so use adverb “fluently”.', explanationWrong:'“Fluent” is an adjective and does not modify the verb directly.', ruleSummary:'Adverbs modify verbs; adjectives modify nouns.', extraExample:'He explained the rules clearly.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'This is a ___ idea for improving my CELPIP writing.', options:['A. well','B. good','C. nicely','D. carefully'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Use adjective “good” before noun “idea”.', explanationWrong:'Adverbs do not modify nouns in this structure.', ruleSummary:'Use adjectives before nouns.', extraExample:'That was a helpful suggestion.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'He worked ___ all week, so he was exhausted by Friday.', options:['A. hard','B. hardly','C. hardness','D. hardily'], answerKey:'A' }, correctAnswer:{ answer:'A' }, explanationCorrect:'“Hard” means with effort.', explanationWrong:'“Hardly” means almost not, which changes the meaning.', ruleSummary:'hard ≠ hardly.', extraExample:'I hardly slept last night.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The instructions were ___ written, so everyone understood them.', options:['A. clear','B. clearly','C. clarity','D. clearing'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Adverb “clearly” modifies the action “written”.', explanationWrong:'Noun/adjective forms are incorrect in this slot.', ruleSummary:'Use adverb to modify past participles used as verbs.', extraExample:'The policy was carefully reviewed.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'After the feedback, I felt ___ about my next attempt.', options:['A. confidently','B. confident','C. confidence','D. more confidently'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'“Felt” is linking verb, so adjective “confident” is needed.', explanationWrong:'Adverbs do not follow linking verbs for states.', ruleSummary:'Linking verbs (feel/seem/be) take adjectives.', extraExample:'She seems nervous today.' },

  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'Please speak ___ so everyone can understand you.', expectedAnswer:'clearly', acceptedAnswers:['clearly'] }, correctAnswer:{ answer:'clearly' }, explanationCorrect:'Adverb modifies speak.', explanationWrong:'Adjective form would be incorrect here.', ruleSummary:'Adverb modifies “speak”.', extraExample:'He answered politely.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'The test was ___, but it was fair.', expectedAnswer:'difficult', acceptedAnswers:['difficult'] }, correctAnswer:{ answer:'difficult' }, explanationCorrect:'Adjective describes the noun/state.', explanationWrong:'Adverb form does not fit after “was”.', ruleSummary:'Adjective describes “test”.', extraExample:'The lesson was useful.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'She handled the customer complaint ___.', expectedAnswer:'calmly', acceptedAnswers:['calmly'] }, correctAnswer:{ answer:'calmly' }, explanationCorrect:'-ly adverb describes how the action was done.', explanationWrong:'Adjective would not modify handled correctly.', ruleSummary:'-ly adverb describes how an action is done.', extraExample:'He responded professionally.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'I feel ___ when I practice speaking with a timer.', expectedAnswer:'anxious', acceptedAnswers:['anxious'] }, correctAnswer:{ answer:'anxious' }, explanationCorrect:'After “feel”, use adjective.', explanationWrong:'Adverb does not work after linking verb feel.', ruleSummary:'After “feel”, use adjective.', extraExample:'He felt confident after training.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct form.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'He arrived late and ___ apologized to the team.', expectedAnswer:'immediately', acceptedAnswers:['immediately'] }, correctAnswer:{ answer:'immediately' }, explanationCorrect:'Adverb modifies apologized.', explanationWrong:'Adjective form would be ungrammatical here.', ruleSummary:'Adverb can modify the verb by showing time/manner.', extraExample:'She quickly checked the email.' },

  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'She drives very careful in the rain.', expectedCorrection:'She drives very carefully in the rain.', acceptedCorrections:['She drives very carefully in the rain.'], errorFocus:'adjective vs adverb' }, correctAnswer:{ answer:'She drives very carefully in the rain.' }, explanationCorrect:'Use adverb to modify drives.', explanationWrong:'“Careful” is adjective and cannot modify the verb directly.', ruleSummary:'Use adverb to modify a verb.', extraExample:'He works efficiently.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'I did good on the practice test.', expectedCorrection:'I did well on the practice test.', acceptedCorrections:['I did well on the practice test.'], errorFocus:'good vs well' }, correctAnswer:{ answer:'I did well on the practice test.' }, explanationCorrect:'Use adverb “well” for performance.', explanationWrong:'“Good” is adjective and sounds unnatural with do in this meaning.', ruleSummary:'“Well” is the adverb form for performance.', extraExample:'She speaks English well.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'I feel confidently about tomorrow’s interview.', expectedCorrection:'I feel confident about tomorrow’s interview.', acceptedCorrections:['I feel confident about tomorrow’s interview.'], errorFocus:'linking verb + adjective' }, correctAnswer:{ answer:'I feel confident about tomorrow’s interview.' }, explanationCorrect:'After feel use adjective confident.', explanationWrong:'Confidently is adverb and incorrect after linking verb.', ruleSummary:'After feel/seem/be, use adjective.', extraExample:'He seems happy today.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'He hardly worked this weekend, so he finished everything early.', expectedCorrection:'He worked hard this weekend, so he finished everything early.', acceptedCorrections:['He worked hard this weekend, so he finished everything early.'], errorFocus:'hard vs hardly (meaning)' }, correctAnswer:{ answer:'He worked hard this weekend, so he finished everything early.' }, explanationCorrect:'Hard means with effort; hardly means almost not.', explanationWrong:'Original sentence creates contradictory meaning.', ruleSummary:'“Hardly” means “almost not”.', extraExample:'I hardly had time to eat.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'The report was careful written.', expectedCorrection:'The report was carefully written.', acceptedCorrections:['The report was carefully written.'], errorFocus:'adverb form' }, correctAnswer:{ answer:'The report was carefully written.' }, explanationCorrect:'Use adverb carefully to modify written.', explanationWrong:'Careful is adjective, not adverb.', ruleSummary:'Use adverb to modify “written”.', extraExample:'The email was clearly structured.' },

  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You are describing your study habits.', task:'Write 3 sentences using 2 adverbs of manner (-ly) and 1 adjective.', targetGrammar:'adjective vs adverb', modelAnswer:'I study quietly in the evening. I review vocabulary carefully before class. This routine is helpful for my confidence.', keyPointsChecklist:['2 adverbs (-ly)','1 adjective','3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Great if you used both adverbs and adjectives in correct roles.', explanationWrong:'Revise if adjective/adverb roles are mixed.', ruleSummary:'Adverbs modify actions; adjectives describe nouns/states.', extraExample:'I practice regularly, and my plan is realistic.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You received feedback that your writing is unclear.', task:'Write 3 sentences explaining how you will improve, using “clearly” and “careful/carefully” correctly.', targetGrammar:'adverb choice + placement', modelAnswer:'I will organize my ideas more clearly. I will carefully check my grammar before submitting. I will ask my instructor for specific feedback.', keyPointsChecklist:['use clearly (adverb)','use carefully (adverb)','3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Strong if clearly/carefully are correctly placed as adverbs.', explanationWrong:'Revise if clear/careful are used where adverbs are required.', ruleSummary:'Choose adverb forms to modify verbs.', extraExample:'I will clearly explain my main point.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Describe a coworker’s professional behavior.', task:'Write 4 sentences using at least one linking verb + adjective (seems/feels) and two adverbs.', targetGrammar:'linking verb + adjective; adverbs', modelAnswer:'My coworker seems calm under pressure. She responds politely to customers. She explains instructions clearly. Her attitude is professional and respectful.', keyPointsChecklist:['linking verb + adjective','2 adverbs','4 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Good work if linking-verb adjective and adverbs are used accurately.', explanationWrong:'Revise if adjectives/adverbs are mixed incorrectly.', ruleSummary:'Linking verbs take adjectives; action verbs can take adverbs.', extraExample:'He seems confident and speaks clearly.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You are writing a short workplace update email.', task:'Write 4 sentences, including one sentence with “hard” and one with “hardly” correctly.', targetGrammar:'hard vs hardly', modelAnswer:'I worked hard to finish the report today. I hardly had time for lunch because of the deadline. The final version is ready for review. Please let me know if you need changes.', keyPointsChecklist:['hard (effort) + hardly (almost not)','4 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Great if hard and hardly are used with correct meanings.', explanationWrong:'Revise if hard/hardly meanings are confused.', ruleSummary:'Hard = with effort; hardly = almost not.', extraExample:'She worked hard but hardly took a break.' },
  { topicSlug:'adjectives_adverbs_manner', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'You want to sound more formal and precise.', task:'Write 3 sentences where each has an adverb placed correctly and one sentence with “well”.', targetGrammar:'adverb placement + well', modelAnswer:'I immediately reviewed the instructions. I completed the task carefully. I performed well during the practice speaking test.', keyPointsChecklist:['correct placement','include “well”','3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Strong if adverbs are placed naturally and well is used correctly.', explanationWrong:'Revise if adverbs are misplaced or if good/well are confused.', ruleSummary:'Adverb placement affects clarity and tone.', extraExample:'I quickly checked the file and answered well.' },


  { topicSlug:'relative_words_choice', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The woman ___ helped me at the Service Canada office was very kind.', options:['A. which','B. who','C. where','D. what'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Use “who” for a person acting as the subject.', explanationWrong:'“Which” is for things, “where” is for places, and “what” does not introduce this kind of relative clause.', ruleSummary:'Use “who” for people, “which” for things, “where” for places, and “whose” for possession.', extraExample:'The advisor who answered my questions was very patient.' },
  { topicSlug:'relative_words_choice', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'This is the printer ___ stopped working this morning.', options:['A. who','B. what','C. which','D. where'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'Use “which” for a thing.', explanationWrong:'“Who” is for people, “where” is for places, and “what” is not used like this here.', ruleSummary:'Use “which” to refer to objects or things.', extraExample:'The laptop which I bought last year is still working well.' },
  { topicSlug:'relative_words_choice', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct word.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'The neighborhood ___ we used to live was much quieter.', expectedAnswer:'where', acceptedAnswers:['where'] }, correctAnswer:{ answer:'where' }, explanationCorrect:'“Where” refers to a place.', explanationWrong:'A person or object word would not fit the meaning.', ruleSummary:'Use “where” for places in relative clauses.', extraExample:'The café where we met is closed now.' },
  { topicSlug:'relative_words_choice', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'The man which interviewed me was very respectful.', expectedCorrection:'The man who interviewed me was very respectful.', acceptedCorrections:['The man who interviewed me was very respectful.'], errorFocus:'who vs which' }, correctAnswer:{ answer:'The man who interviewed me was very respectful.' }, explanationCorrect:'“Who” is correct for people.', explanationWrong:'“Which” is incorrect for a person here.', ruleSummary:'Use “who” for people.', extraExample:'The teacher who explained the lesson was very clear.' },
  { topicSlug:'relative_words_choice', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Describe a teacher, place, or object that helped you recently.', task:'Write 3 sentences using at least one of these words correctly: who, which, where.', targetGrammar:'relative words', modelAnswer:'I spoke to a teacher who gave me useful advice. I also visited a library where I could study quietly. I borrowed a book which explained the topic clearly.', keyPointsChecklist:['uses at least one correct relative word','includes 3 sentences','meaning is clear'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Your response is strong if relative words match people/things/places correctly.', explanationWrong:'Revise if word choice does not match the noun type.', ruleSummary:'Choose relative words based on meaning and grammar role.', extraExample:'The office where I submitted my form was very busy.' },
  { topicSlug:'relative_words_choice', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The student ___ essay won the prize is from Surrey.', options:['A. who','B. whose','C. which','D. what'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'“Whose” shows possession.', explanationWrong:'“Who” cannot show possession by itself in this structure.', ruleSummary:'Use “whose” to show possession.', extraExample:'The employee whose idea improved the process received recognition.' },
  { topicSlug:'relative_words_choice', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I do not understand ___ you mean by that comment.', options:['A. which','B. who','C. what','D. where'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'“What” means “the thing that.”', explanationWrong:'The other options do not match the function here.', ruleSummary:'Use “what” when meaning “the thing that.”', extraExample:'What I need most is more time to practice.' },
  { topicSlug:'relative_words_choice', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct word.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'The candidate to ___ I spoke had previous experience in accounting.', expectedAnswer:'whom', acceptedAnswers:['whom'] }, correctAnswer:{ answer:'whom' }, explanationCorrect:'After a preposition in formal English, “whom” is acceptable for people.', explanationWrong:'“Who” is less standard in this formal exercise context.', ruleSummary:'After a preposition, “whom” can be used in formal English for people.', extraExample:'The person with whom I worked was extremely reliable.' },
  { topicSlug:'relative_words_choice', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'The apartment what we rented was too expensive.', expectedCorrection:'The apartment that we rented was too expensive.', acceptedCorrections:['The apartment that we rented was too expensive.','The apartment which we rented was too expensive.'], errorFocus:'what vs that/which' }, correctAnswer:{ answer:'The apartment that we rented was too expensive.' }, explanationCorrect:'“What” is not used like that to modify a noun here.', explanationWrong:'After a noun, use that/which for this clause.', ruleSummary:'Use “that/which” after a noun, not “what.”', extraExample:'The course that I took was very practical.' },
  { topicSlug:'relative_words_choice', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Explain something important about your studies or work using precise relative words.', task:'Write 4 sentences using at least two of these correctly: whose, what, where, that.', targetGrammar:'relative words, precision', modelAnswer:'I study in a program that requires a lot of practice. My daughter goes to a daycare where she feels comfortable. What helps me most is a clear schedule. I also value teachers whose feedback is specific.', keyPointsChecklist:['uses at least 2 target words correctly','includes 4 sentences','ideas are coherent'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Well done if target words are used naturally and accurately.', explanationWrong:'Revise if words are forced or grammatically mismatched.', ruleSummary:'Accurate relative-word choice improves precision and coherence.', extraExample:'What motivates me is feedback that is specific and useful.' },

  { topicSlug:'enough_usage', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I was not confident ___ to speak in front of the class.', options:['A. enough','B. too','C. very','D. so'], answerKey:'A' }, correctAnswer:{ answer:'A' }, explanationCorrect:'“Enough” comes after adjectives: confident enough.', explanationWrong:'The other options do not complete the structure correctly.', ruleSummary:'enough comes after adjectives and adverbs.', extraExample:'She is calm enough to handle pressure.' },
  { topicSlug:'enough_usage', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'We have ___ chairs for everyone in the room.', options:['A. enough','B. enough of','C. too','D. very'], answerKey:'A' }, correctAnswer:{ answer:'A' }, explanationCorrect:'“Enough” comes before nouns: enough chairs.', explanationWrong:'“Enough of” is not natural here in this basic structure.', ruleSummary:'enough comes before nouns.', extraExample:'Do we have enough time to finish?' },
  { topicSlug:'enough_usage', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct word.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'He did not study hard ___ to pass the exam.', expectedAnswer:'enough', acceptedAnswers:['enough'] }, correctAnswer:{ answer:'enough' }, explanationCorrect:'Enough follows the adverb “hard”.', explanationWrong:'Another position would be incorrect in this sentence.', ruleSummary:'enough comes after adjectives and adverbs.', extraExample:'She did not speak slowly enough.' },
  { topicSlug:'enough_usage', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'I have money enough to buy the book.', expectedCorrection:'I have enough money to buy the book.', acceptedCorrections:['I have enough money to buy the book.'], errorFocus:'enough placement before noun' }, correctAnswer:{ answer:'I have enough money to buy the book.' }, explanationCorrect:'Before a noun, enough comes first: enough money.', explanationWrong:'“Money enough” is unnatural in standard modern English here.', ruleSummary:'enough + noun; adjective/adverb + enough', extraExample:'We do not have enough information yet.' },
  { topicSlug:'enough_usage', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Explain whether you are prepared for a class presentation.', task:'Write 3 sentences using “enough” correctly at least twice.', targetGrammar:'enough placement', modelAnswer:'I have enough notes for my presentation. However, I do not feel confident enough yet. I need enough time tonight to practice again.', keyPointsChecklist:['uses enough at least twice','includes noun use and adjective/adverb use','3 sentences minimum'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Strong response if enough appears in both structures correctly.', explanationWrong:'Revise if enough placement is inconsistent.', ruleSummary:'Place enough after adjectives/adverbs and before nouns.', extraExample:'I was focused enough to finish, and I had enough resources.' },
  { topicSlug:'enough_usage', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The instructions were clear enough ___ everyone understood the process.', options:['A. to','B. for','C. that','D. than'], answerKey:'C' }, correctAnswer:{ answer:'C' }, explanationCorrect:'“Clear enough that…” introduces a result clause.', explanationWrong:'The other options do not fit this structure.', ruleSummary:'enough can be followed by to-infinitive or a result clause with that.', extraExample:'The room was quiet enough that I could focus.' },
  { topicSlug:'enough_usage', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'She is experienced enough ___ this task without supervision.', options:['A. doing','B. to do','C. do','D. done'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Adjective + enough + to + base verb.', explanationWrong:'Other forms are ungrammatical in this pattern.', ruleSummary:'adjective + enough + to-infinitive', extraExample:'He is mature enough to accept feedback.' },
  { topicSlug:'enough_usage', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct word.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'We were lucky ___ to find parking near the clinic.', expectedAnswer:'enough', acceptedAnswers:['enough'] }, correctAnswer:{ answer:'enough' }, explanationCorrect:'Enough follows the adjective lucky.', explanationWrong:'Different placement would break the structure.', ruleSummary:'adjective + enough', extraExample:'She was organized enough to finish early.' },
  { topicSlug:'enough_usage', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'He is enough strong to carry that box alone.', expectedCorrection:'He is strong enough to carry that box alone.', acceptedCorrections:['He is strong enough to carry that box alone.'], errorFocus:'enough placement after adjective' }, correctAnswer:{ answer:'He is strong enough to carry that box alone.' }, explanationCorrect:'Enough comes after adjectives, not before.', explanationWrong:'“Enough strong” is incorrect word order.', ruleSummary:'adjective + enough', extraExample:'She is patient enough to work with children.' },
  { topicSlug:'enough_usage', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Describe whether a job candidate is suitable for a position.', task:'Write 4 sentences using “enough” in two different structures.', targetGrammar:'enough with noun and adjective', modelAnswer:'The candidate has enough experience for the role. She also seems confident enough to speak with clients. However, she may not have enough technical knowledge yet. Overall, she is strong enough for an entry-level position.', keyPointsChecklist:['uses enough with noun and adjective','4 sentences','meaning is clear and practical'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Great if both enough patterns are used naturally.', explanationWrong:'Revise if only one pattern appears or placement is incorrect.', ruleSummary:'Use enough flexibly with nouns and adjective/adverb structures.', extraExample:'We had enough data, and the team was prepared enough to proceed.' },

  { topicSlug:'obligation_modals', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'You ___ wear a seatbelt while driving in British Columbia.', options:['A. should','B. must','C. could','D. might'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'“Must” expresses strong obligation/rule.', explanationWrong:'“Should” is advice, not a strict rule here.', ruleSummary:'must = strong obligation; should = advice.', extraExample:'Employees must follow safety rules.' },
  { topicSlug:'obligation_modals', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I ___ finish this form today because the deadline is tomorrow.', options:['A. have to','B. might','C. would','D. can'], answerKey:'A' }, correctAnswer:{ answer:'A' }, explanationCorrect:'“Have to” expresses necessity due to circumstances.', explanationWrong:'Other options do not express obligation correctly.', ruleSummary:'have to = external necessity; must = strong obligation/rule.', extraExample:'I have to pick up my daughter at 5.' },
  { topicSlug:'obligation_modals', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct modal.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'You ___ talk to your instructor if you are confused about the assignment.', expectedAnswer:'should', acceptedAnswers:['should'] }, correctAnswer:{ answer:'should' }, explanationCorrect:'Should is used for advice.', explanationWrong:'Stronger obligation forms would change the meaning.', ruleSummary:'should = recommendation/advice.', extraExample:'You should ask for clarification early.' },
  { topicSlug:'obligation_modals', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'I must to leave now because my bus is coming.', expectedCorrection:'I must leave now because my bus is coming.', acceptedCorrections:['I must leave now because my bus is coming.'], errorFocus:'must + base verb' }, correctAnswer:{ answer:'I must leave now because my bus is coming.' }, explanationCorrect:'Must is followed directly by base verb.', explanationWrong:'“Must to leave” is incorrect.', ruleSummary:'must + base verb; no “to”.', extraExample:'You must be careful on icy roads.' },
  { topicSlug:'obligation_modals', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Give advice to a new student in Canada.', task:'Write 3 sentences using must, have to, and should.', targetGrammar:'obligation and advice', modelAnswer:'You must check important deadlines carefully. You have to attend class regularly if you want good results. You should also ask questions when you do not understand something.', keyPointsChecklist:['uses must, have to, and should','3 sentences','advice/obligation is practical'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Good if each modal is used with the intended meaning.', explanationWrong:'Revise if meanings of must/have to/should are mixed.', ruleSummary:'Different modals express rule, necessity, or advice.', extraExample:'You should review weekly, and you must submit required forms.' },
  { topicSlug:'obligation_modals', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'Employees are ___ submit their timesheets by Friday noon.', options:['A. supposed','B. supposed to','C. have','D. should to'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Be supposed to expresses expectation or rule.', explanationWrong:'Other options are incomplete or incorrect forms.', ruleSummary:'be supposed to + base verb', extraExample:'Students are supposed to bring their ID cards.' },
  { topicSlug:'obligation_modals', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'You do not ___ bring food, but you may if you want.', options:['A. must','B. have to','C. should','D. supposed to'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Do not have to means not necessary.', explanationWrong:'Must not would mean prohibited.', ruleSummary:'do not have to = lack of necessity; must not = prohibition.', extraExample:'You do not have to come early tomorrow.' },
  { topicSlug:'obligation_modals', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct base verb.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'Visitors must not ___ in this area of the building.', expectedAnswer:'smoke', acceptedAnswers:['smoke'] }, correctAnswer:{ answer:'smoke' }, explanationCorrect:'After must not, use base verb.', explanationWrong:'Other forms are grammatically incorrect after modals.', ruleSummary:'modal + base verb', extraExample:'You must not park here.' },
  { topicSlug:'obligation_modals', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'You do not must finish it tonight.', expectedCorrection:'You do not have to finish it tonight.', acceptedCorrections:['You do not have to finish it tonight.'], errorFocus:'negative obligation form' }, correctAnswer:{ answer:'You do not have to finish it tonight.' }, explanationCorrect:'Standard English uses do not have to for lack of necessity.', explanationWrong:'“Do not must” is not standard.', ruleSummary:'Use do not have to or must not depending on meaning.', extraExample:'You do not have to decide right away.' },
  { topicSlug:'obligation_modals', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Explain the rules and expectations for a new workplace.', task:'Write 4 sentences using at least three of these correctly: must, have to, should, be supposed to, must not.', targetGrammar:'obligation distinctions', modelAnswer:'Employees must wear their ID badges at all times. They have to complete safety training in the first week. They are supposed to arrive on time for meetings. They must not share confidential information.', keyPointsChecklist:['uses at least 3 target forms correctly','shows rule vs advice vs expectation if possible','4 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Strong if modal meanings are clearly distinguished.', explanationWrong:'Revise if forms are grammatically correct but meanings are mixed.', ruleSummary:'Modal choices communicate different obligation strength and source.', extraExample:'You should ask questions, but you must follow safety rules.' },

  { topicSlug:'going_to_vs_will', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I bought the ingredients yesterday, so I am ___ make soup tonight.', options:['A. will','B. going to','C. went to','D. go to'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Be going to is used for a prior plan/intention.', explanationWrong:'Will is less natural when decision was already made.', ruleSummary:'going to = plan/intention; will = spontaneous decision/prediction/promise', extraExample:'We are going to visit my in-laws this weekend.' },
  { topicSlug:'going_to_vs_will', difficulty:'intermediate', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'The phone is ringing. I ___ get it.', options:['A. am going to','B. will','C. going to','D. am'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Will is natural for a spontaneous decision at speaking time.', explanationWrong:'Going to suggests a prior plan.', ruleSummary:'will often expresses immediate decisions.', extraExample:'I will open the door.' },
  { topicSlug:'going_to_vs_will', difficulty:'intermediate', type:'fill_blank', prompt:'Fill in the blank with the correct phrase.', instructions:'Type the full phrase.', questionData:{ sentenceWithBlank:'Look at those dark clouds. It ___ rain soon.', expectedAnswer:'is going to', acceptedAnswers:['is going to','it is going to',"it's going to"] }, correctAnswer:{ answer:'is going to' }, explanationCorrect:'Going to is best for prediction based on present evidence.', explanationWrong:'Will can be possible, but evidence-based prediction favors going to here.', ruleSummary:'Use going to for evidence-based predictions.', extraExample:'Be careful. You are going to drop that box.' },
  { topicSlug:'going_to_vs_will', difficulty:'intermediate', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'I will going to study tonight after dinner.', expectedCorrection:'I am going to study tonight after dinner.', acceptedCorrections:['I am going to study tonight after dinner.'], errorFocus:'future form mixing' }, correctAnswer:{ answer:'I am going to study tonight after dinner.' }, explanationCorrect:'Do not combine will and going to in one verb phrase.', explanationWrong:'Only one future structure should be used.', ruleSummary:'Choose one future pattern: will or be going to.', extraExample:'I am going to review conditionals tonight.' },
  { topicSlug:'going_to_vs_will', difficulty:'intermediate', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Tell a friend about your plans for tomorrow and one spontaneous decision.', task:'Write 3 sentences using both going to and will.', targetGrammar:'future contrast', modelAnswer:'I am going to wake up early tomorrow. I am going to review grammar before class. If my teacher sends extra homework, I will do it in the evening.', keyPointsChecklist:['uses going to for plan','uses will for spontaneous response or future reaction','3 sentences'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Good if going to and will are used for different future meanings.', explanationWrong:'Revise if both forms are used randomly without meaning contrast.', ruleSummary:'Future choice depends on intention, evidence, and spontaneity.', extraExample:'I am going to cook, but I will order food if I get home late.' },
  { topicSlug:'going_to_vs_will', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'I think the course ___ help you feel more confident, but I am not completely sure.', options:['A. is going to','B. will','C. going','D. am going'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'Will is common with opinion phrases like I think.', explanationWrong:'Going to is less natural here without strong present evidence.', ruleSummary:'Will often follows think/probably/I guess for predictions.', extraExample:'I think she will do well on the exam.' },
  { topicSlug:'going_to_vs_will', difficulty:'advanced', type:'multiple_choice', prompt:'Choose the correct option.', instructions:'Select one answer.', questionData:{ sentence:'We ___ apply for permanent residency after graduation; we have already discussed the timeline.', options:['A. will','B. are going to','C. go to','D. will to'], answerKey:'B' }, correctAnswer:{ answer:'B' }, explanationCorrect:'This is a prior intention/plan.', explanationWrong:'Will is possible, but going to better matches planned intention.', ruleSummary:'Be going to for established plans.', extraExample:'They are going to move next summer.' },
  { topicSlug:'going_to_vs_will', difficulty:'advanced', type:'fill_blank', prompt:'Fill in the blank with the correct modal.', instructions:'Type one word.', questionData:{ sentenceWithBlank:'I just got your message. I ___ reply as soon as I finish this task.', expectedAnswer:'will', acceptedAnswers:['will',"i'll",'i will','I will',"I'll"] }, correctAnswer:{ answer:'will' }, explanationCorrect:'Will is natural for a decision/promise made now.', explanationWrong:'Going to would imply a prior intention.', ruleSummary:'Use will for spontaneous decisions and promises.', extraExample:'I will call you later tonight.' },
  { topicSlug:'going_to_vs_will', difficulty:'advanced', type:'error_correction', prompt:'Correct the sentence.', instructions:'Rewrite the sentence correctly.', questionData:{ incorrectSentence:'We are going to probably need more time.', expectedCorrection:'We will probably need more time.', acceptedCorrections:['We will probably need more time.'], errorFocus:'natural prediction form' }, correctAnswer:{ answer:'We will probably need more time.' }, explanationCorrect:'Will probably is more natural for uncertain prediction.', explanationWrong:'Original sentence is awkward in this context.', ruleSummary:'Will works naturally with probably/think/maybe for predictions.', extraExample:'It will probably take longer than expected.' },
  { topicSlug:'going_to_vs_will', difficulty:'advanced', type:'mini_production', prompt:'Write a short response.', instructions:'Use the target grammar and follow the checklist.', questionData:{ scenario:'Explain your plans for the next week and make two predictions.', task:'Write 4 sentences using going to for plans and will for predictions/promises.', targetGrammar:'going to vs will', modelAnswer:'I am going to finish two grammar units this week. I am also going to practice speaking every evening. I think this routine will improve my fluency. It will probably help me feel more confident during timed tasks.', keyPointsChecklist:['uses going to for plans','uses will for predictions','4 sentences','meaning is clear'] }, correctAnswer:{ mode:'self_review' }, explanationCorrect:'Strong if the future forms match their functions.', explanationWrong:'Revise if plan/prediction forms are mixed without meaning.', ruleSummary:'Choose going to for plans and will for predictions/reactions.', extraExample:'I am going to review tonight, and I think I will perform better tomorrow.' },

];

async function main() {
  validateSeedData();
  await prisma.attempt.deleteMany();
  await prisma.studySession.deleteMany();
  await prisma.dailyAssignmentHistory.deleteMany();
  await prisma.topicStats.deleteMany();
  await prisma.exercise.deleteMany();
  await prisma.topic.deleteMany();
  await prisma.appSettings.deleteMany();


  await prisma.appSettings.upsert({
    where: { id: 1 },
    create: { id: 1, defaultDailyTopics: 3, intensiveMode: false },
    update: {},
  });

  const createdTopics = new Map<string, number>();

  for (const [slug, name, description, cefrRange] of topics) {
    const topic = await prisma.topic.create({
      data: { slug, name, description, cefrRange, isActive: true },
    });
    createdTopics.set(slug, topic.id);

    await prisma.topicStats.create({ data: { topicId: topic.id } });
  }

  for (const ex of exercises) {
    await prisma.exercise.create({
      data: {
        topicId: createdTopics.get(ex.topicSlug)!,
        difficulty: ex.difficulty,
        type: ex.type,
        prompt: ex.prompt,
        instructions: ex.instructions,
        questionData: serializeJson(ex.questionData),
        correctAnswer: serializeJson(ex.correctAnswer),
        explanationCorrect: ex.explanationCorrect,
        explanationWrong: ex.explanationWrong,
        ruleSummary: ex.ruleSummary,
        extraExample: ex.extraExample,
        tags: serializeJson([ex.topicSlug, ex.difficulty, ex.type]),
        sourceType: 'seeded',
        isActive: true,
      },
    });
  }

  if (exercises.length !== 120) throw new Error(`Expected 120 exercises but found ${exercises.length}`);
  console.log(`Seed complete: ${topics.length} topics, ${exercises.length} exercises.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
